-- Write your SQL code here
DELIMITER /
/

CREATE PROCEDURE SP_INSERT_PRODUCT(
    IN P_PRODUCTID INT,
    IN P_PRODUCTNAME VARCHAR(255),
    IN P_PRODUCTPRICE DECIMAL(10, 2),
    IN P_PRODUCTCATEGORY VARCHAR(255),
    IN P_PRODUCTQUANTITY INT
)