-- Write your SQL code here
DELIMITER

/

/

CREATE PROCEDURE SP_INSERT_PRODUCT(
    IN P_PRODUCTID INT,
    IN P_PRODUCTNAME VARCHAR(255),
    IN P_PRODUCTPRICE DECIMAL(10, 2),
    IN P_PRODUCTCATEGORY VARCHAR(255),
    IN P_PRODUCTQUANTITY INT
)
BEGIN
    INSERT INTO PRODUCT(
        PRODUCTID,
        PRODUCTNAME,
        PRODUCTPRICE,
        PRODUCTCATEGORY,
        PRODUCTQUANTITY
    ) VALUES (
        P_PRODUCTID,
        P_PRODUCTNAME,
        P_PRODUCTPRICE,
        P_PRODUCTCATEGORY,
        P_PRODUCTQUANTITY
    );
END // DELIMITER;
 

-- testing the stored PROCEDURE
CALL SP_INSERT_PRODUCT(301, 'Marlaboro', 250, 'Cigarette', 500 );
 
-- Table Storage insertion.
DELIMITER // CREATE PROCEDURE SP_INSERT_STORAGE( IN P_STORAGEID INT, IN P_STORAGELOCATION VARCHAR(255), IN P_STORAGECAPACITY INT );
BEGIN
    INSERT INTO STORAGE(
        STORAGEID,
        STORAGELOCATION,
        STORAGECAPACITY
    ) VALUES (
        P_STORAGEID,
        P_STORAGELOCATION,
        P_STORAGECAPACITY
    );
END /
/