-- Write YOUR SQL code here

CREATE FUNCTION CALCULATETOTALORDERAMOUNT(
    P_ORDERID INT
) RETURNS DECIMAL(10, 2) DETERMINISTIC
BEGIN
    DECLARE V_TOTAL_AMOUNT DECIMAL(10, 2);
    SELECT
        SUM(PRODUCTPRICE * QUANTITY) INTO V_TOTAL_AMOUNT
    FROM
        ORDER_DETAILS
    WHERE
        ORDERID = P_ORDERID;
    RETURN V_TOTAL_AMOUNT;
END /
/